language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ZjeLGf/mIBLkUDZJuYUMQx/3Hgkplb91lBlM+0oM0bQXDnSWKyU81PnB75I5WQkTgoKAZ7j9OjjT0epNwynXJjyV+wK84Dx0B/AgQaHhDCvsqOXE4V6JFN95e/XVHqu0QAwqxH3s/XYBnEAh08ijplM1lOOkPVw9ggywT5v96Uh0LuwQjm/RScOG0uZNJoO4fLR0+FprLqvAVQ0VYdHvzX2MrVk+68LGm9SL5fL20uKGJKAEjrv0uqez42iYr1tvqrczJCfHndbYd3aXIDz6wzRNpM3IRnVrYFulXZgx8gZHjyLhtfJNikhYLG7wbGzeOQPBV/YXeu2PJfWljl2LiY7HlTwONkIIAZNHIIf8wbEdc0+mPZc5B0mxg+0APYF7/+sXnsOBM8c00bqWy1SpH/1haO3BxOnYNStFNzaeQN1nZfL1W9c2w92yYsxZ+tRaa5f/s9K7tl4m9Fyaf/orCcEUU76yLdCOozHMIxN9aFYZXFiHImEZwJa5h5Wt/C3gMG+KzKxXh9EYM6yQI6jAqaZEwDt+vv1CVMtHZLu1FCyLB27nnUCQhmk/wGYu7g3Ti9TQ5qZ+vU2LM/axvxswmJZ28xl7k+dhXkp3BsRz0vTIjcLJvogpR4EF8S5keksBMrLxyCFhPZRbD0oJ2dUOTULgBcw1X+duJgbR0uM0Uf8=
  app: polar-waters-95107
  on:
    repo: elliotkim916/marvel_encyclopedia_api
